// seedQuestions.js
import mongoose from "mongoose";
import dotenv from "dotenv";
import Question from "./models/questions.js";

dotenv.config();

const questions = [
  {"topic":"Science","questionText":"What is the chemical symbol for water?","options":["H2O","O2","CO2","HO"],"correctIndex":0},
  {"topic":"Science","questionText":"Which planet is known as the Red Planet?","options":["Mars","Venus","Jupiter","Saturn"],"correctIndex":0},
  {"topic":"Science","questionText":"What gas do plants absorb from the atmosphere?","options":["Oxygen","Carbon Dioxide","Nitrogen","Hydrogen"],"correctIndex":1},
  {"topic":"Science","questionText":"Which part of the cell contains genetic material?","options":["Nucleus","Cytoplasm","Cell Membrane","Mitochondria"],"correctIndex":0},
  {"topic":"Science","questionText":"What is the speed of light?","options":["300,000 km/s","150,000 km/s","100,000 km/s","1,000 km/s"],"correctIndex":0},
  {"topic":"Science","questionText":"Which organ in the human body pumps blood?","options":["Heart","Liver","Kidney","Lungs"],"correctIndex":0},
  {"topic":"Science","questionText":"Which gas is most abundant in Earth's atmosphere?","options":["Oxygen","Carbon Dioxide","Nitrogen","Hydrogen"],"correctIndex":2},
  {"topic":"Science","questionText":"What is the main source of energy for the Earth?","options":["Moon","Sun","Stars","Wind"],"correctIndex":1},
  {"topic":"Science","questionText":"Which planet is closest to the Sun?","options":["Mercury","Venus","Earth","Mars"],"correctIndex":0},
  {"topic":"Science","questionText":"What force keeps us on the ground?","options":["Magnetism","Friction","Gravity","Electricity"],"correctIndex":2},
  {"topic":"Science","questionText":"Which element is used in pencils?","options":["Graphite","Lead","Carbon","Aluminium"],"correctIndex":0},
  {"topic":"Science","questionText":"What vitamin is produced when skin is exposed to sunlight?","options":["Vitamin A","Vitamin B","Vitamin C","Vitamin D"],"correctIndex":3},
  {"topic":"Science","questionText":"Which planet has rings?","options":["Jupiter","Saturn","Mars","Venus"],"correctIndex":1},
  {"topic":"Science","questionText":"Water boils at what temperature at sea level?","options":["90°C","100°C","110°C","120°C"],"correctIndex":1},
  {"topic":"Science","questionText":"Which gas is released during photosynthesis?","options":["Oxygen","Carbon Dioxide","Nitrogen","Hydrogen"],"correctIndex":0},
  {"topic":"Science","questionText":"What is the hardest natural substance on Earth?","options":["Gold","Iron","Diamond","Quartz"],"correctIndex":2},
  {"topic":"Science","questionText":"Which organ filters blood in the human body?","options":["Liver","Kidney","Lungs","Heart"],"correctIndex":1},
  {"topic":"Science","questionText":"Lightning is caused by?","options":["Friction in clouds","Sun","Wind","Rain"],"correctIndex":0},
  {"topic":"Science","questionText":"What is HCl commonly known as?","options":["Vinegar","Hydrochloric acid","Bleach","Ammonia"],"correctIndex":1},
  {"topic":"Science","questionText":"Which planet is known for its Great Red Spot?","options":["Earth","Mars","Jupiter","Saturn"],"correctIndex":2},
  {"topic":"Science","questionText":"Which gas do humans exhale?","options":["Oxygen","Carbon Dioxide","Nitrogen","Hydrogen"],"correctIndex":1},
  {"topic":"Science","questionText":"Sound travels fastest in which medium?","options":["Air","Water","Steel","Vacuum"],"correctIndex":2},
  {"topic":"Science","questionText":"Which part of the brain controls balance?","options":["Cerebellum","Cerebrum","Brainstem","Hypothalamus"],"correctIndex":0},
  {"topic":"Science","questionText":"Which organ produces insulin?","options":["Liver","Pancreas","Kidney","Heart"],"correctIndex":1},
  {"topic":"Science","questionText":"The boiling point of water decreases with?","options":["Altitude","Pressure","Temperature","Volume"],"correctIndex":0},
  {"topic":"Science","questionText":"What is the center of an atom called?","options":["Electron","Proton","Nucleus","Neutron"],"correctIndex":2},
  {"topic":"Science","questionText":"Which element has the atomic number 1?","options":["Helium","Hydrogen","Oxygen","Carbon"],"correctIndex":1},
  {"topic":"Science","questionText":"The human skeleton is made of?","options":["Cartilage","Bone","Muscle","Ligament"],"correctIndex":1},
  {"topic":"Science","questionText":"Which planet is known as the Earth's twin?","options":["Mars","Venus","Mercury","Jupiter"],"correctIndex":1},
  {"topic":"Science","questionText":"What type of energy is stored in food?","options":["Mechanical","Chemical","Electrical","Nuclear"],"correctIndex":1},
  {"topic":"Science","questionText":"Which is the smallest unit of life?","options":["Atom","Cell","Molecule","Organ"],"correctIndex":1},
  {"topic":"Science","questionText":"Which gas is essential for breathing?","options":["Nitrogen","Oxygen","Carbon Dioxide","Helium"],"correctIndex":1},
  {"topic":"Science","questionText":"What is the boiling point of nitrogen?","options":["-196°C","0°C","100°C","-50°C"],"correctIndex":0},
  {"topic":"Science","questionText":"Which planet is farthest from the Sun?","options":["Neptune","Uranus","Saturn","Jupiter"],"correctIndex":0},
  {"topic":"Science","questionText":"Which organ stores bile?","options":["Liver","Gallbladder","Pancreas","Stomach"],"correctIndex":1},
  {"topic":"Science","questionText":"Which gas causes acid rain?","options":["Oxygen","Sulfur dioxide","Nitrogen","Carbon dioxide"],"correctIndex":1},
  {"topic":"Science","questionText":"Which metal is liquid at room temperature?","options":["Mercury","Iron","Lead","Gold"],"correctIndex":0},
  {"topic":"Science","questionText":"The Earth rotates on its?","options":["Orbit","Axis","Equator","Pole"],"correctIndex":1},
  {"topic":"Science","questionText":"Which organ helps in digestion of fats?","options":["Liver","Gallbladder","Stomach","Pancreas"],"correctIndex":1},
  {"topic":"Science","questionText":"The largest organ in the human body is?","options":["Heart","Liver","Skin","Lung"],"correctIndex":2},
  {"topic":"Science","questionText":"Which part of the eye controls light entering?","options":["Iris","Pupil","Cornea","Retina"],"correctIndex":0},
  {"topic":"Science","questionText":"Which process converts solid directly to gas?","options":["Condensation","Sublimation","Evaporation","Freezing"],"correctIndex":1},
  {"topic":"Science","questionText":"What is the chemical formula of table salt?","options":["NaCl","KCl","Na2CO3","CaCl2"],"correctIndex":0},
  {"topic":"Science","questionText":"Which blood cells fight infections?","options":["Red blood cells","White blood cells","Platelets","Plasma"],"correctIndex":1},
  {"topic":"Science","questionText":"Which vitamin is water soluble?","options":["Vitamin A","Vitamin C","Vitamin D","Vitamin K"],"correctIndex":1},
  {"topic":"Science","questionText":"Which planet has the fastest rotation?","options":["Jupiter","Earth","Saturn","Mars"],"correctIndex":0},
  {"topic":"Science","questionText":"What is the main gas in natural gas?","options":["Methane","Oxygen","Carbon Dioxide","Hydrogen"],"correctIndex":0},
  // Continue similarly for Math, History, Sports
   {"topic":"Math","questionText":"What is 12 × 8?","options":["96","88","108","102"],"correctIndex":0},
  {"topic":"Math","questionText":"What is the square root of 144?","options":["12","14","16","10"],"correctIndex":0},
  {"topic":"Math","questionText":"What is 15 + 27?","options":["42","40","43","41"],"correctIndex":0},
  {"topic":"Math","questionText":"What is 50 ÷ 5?","options":["10","15","5","12"],"correctIndex":0},
  {"topic":"Math","questionText":"What is 7 × 9?","options":["63","56","72","64"],"correctIndex":0},
  {"topic":"Math","questionText":"What is the value of π (pi) up to 2 decimal places?","options":["3.14","3.15","3.13","3.12"],"correctIndex":0},
  {"topic":"Math","questionText":"What is 2³?","options":["8","6","4","9"],"correctIndex":0},
  {"topic":"Math","questionText":"If x + 5 = 12, what is x?","options":["7","8","6","5"],"correctIndex":0},
  {"topic":"Math","questionText":"What is the perimeter of a square with side 5?","options":["20","25","15","10"],"correctIndex":0},
  {"topic":"Math","questionText":"What is the area of a rectangle with length 8 and width 4?","options":["32","24","30","36"],"correctIndex":0},
  {"topic":"Math","questionText":"What is 9²?","options":["81","72","90","79"],"correctIndex":0},
  {"topic":"Math","questionText":"What is 100 ÷ 25?","options":["4","5","6","3"],"correctIndex":0},
  {"topic":"Math","questionText":"What is the next prime number after 7?","options":["11","9","13","17"],"correctIndex":0},
  {"topic":"Math","questionText":"What is 0.5 × 8?","options":["4","3","5","2"],"correctIndex":0},
  {"topic":"Math","questionText":"If 5x = 20, what is x?","options":["4","5","3","6"],"correctIndex":0},
  {"topic":"Math","questionText":"What is the sum of angles in a triangle?","options":["180°","90°","360°","270°"],"correctIndex":0},
  {"topic":"Math","questionText":"What is the square root of 225?","options":["15","14","12","13"],"correctIndex":0},
  {"topic":"Math","questionText":"What is 3 × 11?","options":["33","30","31","32"],"correctIndex":0},
  {"topic":"Math","questionText":"What is 50% of 200?","options":["100","90","120","80"],"correctIndex":0},
  {"topic":"Math","questionText":"What is 7 + 8 × 2?","options":["23","30","15","16"],"correctIndex":0},
  {"topic":"Math","questionText":"What is the cube of 3?","options":["27","9","18","21"],"correctIndex":0},
  {"topic":"Math","questionText":"What is 45 ÷ 9?","options":["5","6","4","7"],"correctIndex":0},
  {"topic":"Math","questionText":"If y - 6 = 10, what is y?","options":["16","14","15","12"],"correctIndex":0},
  {"topic":"Math","questionText":"What is the factorial of 4?","options":["24","16","12","18"],"correctIndex":0},
  {"topic":"Math","questionText":"What is the perimeter of a triangle with sides 3, 4, 5?","options":["12","10","11","9"],"correctIndex":0},
  {"topic":"Math","questionText":"What is the value of 2² + 3²?","options":["13","12","14","11"],"correctIndex":0},
  {"topic":"Math","questionText":"What is 1/2 + 1/3?","options":["5/6","2/5","3/5","1/5"],"correctIndex":0},
  {"topic":"Math","questionText":"What is the next even number after 48?","options":["50","52","49","51"],"correctIndex":0},
  {"topic":"Math","questionText":"What is the product of 6 × 7?","options":["42","36","48","40"],"correctIndex":0},
  {"topic":"Math","questionText":"What is 0.25 × 16?","options":["4","5","3","6"],"correctIndex":0},
  {"topic":"Math","questionText":"What is the difference between 100 and 45?","options":["55","50","65","60"],"correctIndex":0},
  {"topic":"Math","questionText":"What is 2 × 5 + 3?","options":["13","12","15","10"],"correctIndex":0},
  {"topic":"Math","questionText":"What is the sum of first 5 natural numbers?","options":["15","10","20","12"],"correctIndex":0},
  {"topic":"Math","questionText":"What is 81 ÷ 9?","options":["9","8","10","7"],"correctIndex":0},
  {"topic":"Math","questionText":"If 3x + 4 = 19, what is x?","options":["5","6","4","3"],"correctIndex":0},
  {"topic":"Math","questionText":"What is the area of a circle with radius 7? (π = 3.14)","options":["153.86","140","160","149"],"correctIndex":0},
  {"topic":"Math","questionText":"What is 2/5 of 50?","options":["20","25","15","10"],"correctIndex":0},
  {"topic":"Math","questionText":"What is the next prime number after 13?","options":["17","15","19","16"],"correctIndex":0},
  {"topic":"Math","questionText":"What is 0.1 × 1000?","options":["100","10","50","200"],"correctIndex":0},
  {"topic":"Math","questionText":"What is 5³?","options":["125","100","115","120"],"correctIndex":0},
  {"topic":"Math","questionText":"What is the difference between 81 and 27?","options":["54","56","50","60"],"correctIndex":0},
  {"topic":"Math","questionText":"What is 14 ÷ 2 + 6?","options":["13","10","12","11"],"correctIndex":0},
  {"topic":"Math","questionText":"What is the product of first 4 prime numbers?","options":["210","200","180","220"],"correctIndex":0},
  {"topic":"Math","questionText":"What is the sum of angles in a quadrilateral?","options":["360°","180°","270°","400°"],"correctIndex":0},
  {"topic":"Math","questionText":"What is 0.75 × 20?","options":["15","12","18","16"],"correctIndex":0},
  {"topic":"Math","questionText":"If x/5 = 6, what is x?","options":["30","25","35","20"],"correctIndex":0},
  {"topic":"Math","questionText":"What is the square of 15?","options":["225","215","230","240"],"correctIndex":0},
  {"topic":"Math","questionText":"What is the next multiple of 7 after 28?","options":["35","36","34","32"],"correctIndex":0},
  {"topic":"Math","questionText":"What is 3/4 of 32?","options":["24","25","22","26"],"correctIndex":0},
  {"topic":"Math","questionText":"What is the perimeter of a rectangle with length 10 and width 5?","options":["30","25","35","28"],"correctIndex":0},
  {"topic":"Math","questionText":"What is 11 × 11?","options":["121","111","131","122"],"correctIndex":0},
  {"topic":"Math","questionText":"What is 2² + 4²?","options":["20","18","16","22"],"correctIndex":0},
  {"topic":"History","questionText":"Who was the first President of the United States?","options":["George Washington","Thomas Jefferson","Abraham Lincoln","John Adams"],"correctIndex":0},
{"topic":"History","questionText":"In which year did World War II end?","options":["1945","1944","1939","1940"],"correctIndex":0},
{"topic":"History","questionText":"Who discovered America in 1492?","options":["Christopher Columbus","Vasco da Gama","Ferdinand Magellan","James Cook"],"correctIndex":0},
{"topic":"History","questionText":"Which empire was ruled by Julius Caesar?","options":["Roman Empire","Ottoman Empire","Mongol Empire","British Empire"],"correctIndex":0},
{"topic":"History","questionText":"Who was known as the 'Maid of Orléans'?","options":["Joan of Arc","Cleopatra","Queen Victoria","Marie Curie"],"correctIndex":0},
{"topic":"History","questionText":"Which year did India gain independence?","options":["1947","1950","1945","1942"],"correctIndex":0},
{"topic":"History","questionText":"Who was the first emperor of China?","options":["Qin Shi Huang","Han Wudi","Emperor Meiji","Kublai Khan"],"correctIndex":0},
{"topic":"History","questionText":"The Great Fire of London occurred in which year?","options":["1666","1600","1700","1750"],"correctIndex":0},
{"topic":"History","questionText":"Who invented the printing press?","options":["Johannes Gutenberg","Thomas Edison","Alexander Graham Bell","Nikola Tesla"],"correctIndex":0},
{"topic":"History","questionText":"The Berlin Wall fell in which year?","options":["1989","1990","1985","1991"],"correctIndex":0},
{"topic":"History","questionText":"Who was the first Prime Minister of India?","options":["Jawaharlal Nehru","Indira Gandhi","Mahatma Gandhi","Rajendra Prasad"],"correctIndex":0},
{"topic":"History","questionText":"The French Revolution began in which year?","options":["1789","1776","1799","1804"],"correctIndex":0},
{"topic":"History","questionText":"Who was the 'Iron Lady'?","options":["Margaret Thatcher","Indira Gandhi","Angela Merkel","Golda Meir"],"correctIndex":0},
{"topic":"History","questionText":"Who was the last pharaoh of Egypt?","options":["Cleopatra","Tutankhamun","Ramses II","Nefertiti"],"correctIndex":0},
{"topic":"History","questionText":"The Magna Carta was signed in which year?","options":["1215","1315","1415","1515"],"correctIndex":0},
{"topic":"History","questionText":"Who led the Soviet Union during World War II?","options":["Joseph Stalin","Vladimir Lenin","Nikita Khrushchev","Mikhail Gorbachev"],"correctIndex":0},
{"topic":"History","questionText":"The American Civil War was fought between which years?","options":["1861-1865","1850-1854","1870-1875","1860-1864"],"correctIndex":0},
{"topic":"History","questionText":"Who discovered penicillin?","options":["Alexander Fleming","Marie Curie","Louis Pasteur","Isaac Newton"],"correctIndex":0},
{"topic":"History","questionText":"Who was the first Emperor of the Roman Empire?","options":["Augustus","Julius Caesar","Nero","Caligula"],"correctIndex":0},
{"topic":"History","questionText":"The Renaissance began in which country?","options":["Italy","France","England","Germany"],"correctIndex":0},
{"topic":"History","questionText":"Who wrote the Declaration of Independence?","options":["Thomas Jefferson","Benjamin Franklin","George Washington","John Adams"],"correctIndex":0},
{"topic":"History","questionText":"The Russian Revolution happened in which year?","options":["1917","1905","1922","1939"],"correctIndex":0},
{"topic":"History","questionText":"Who was the founder of the Mughal Empire in India?","options":["Babur","Akbar","Shah Jahan","Aurangzeb"],"correctIndex":0},
{"topic":"History","questionText":"The Cold War was mainly between which two countries?","options":["USA and USSR","USA and Germany","USA and China","USA and UK"],"correctIndex":0},
{"topic":"History","questionText":"Who was the first human to journey into space?","options":["Yuri Gagarin","Neil Armstrong","Buzz Aldrin","John Glenn"],"correctIndex":0},
{"topic":"History","questionText":"The Opium Wars were fought between which countries?","options":["China and Britain","China and France","China and USA","China and Japan"],"correctIndex":0},
{"topic":"History","questionText":"Who was the first chancellor of Germany?","options":["Otto von Bismarck","Adolf Hitler","Konrad Adenauer","Wilhelm II"],"correctIndex":0},
{"topic":"History","questionText":"Who painted the Mona Lisa?","options":["Leonardo da Vinci","Michelangelo","Raphael","Donatello"],"correctIndex":0},
{"topic":"History","questionText":"The Battle of Hastings was fought in which year?","options":["1066","1050","1075","1088"],"correctIndex":0},
{"topic":"History","questionText":"Who was the first female Prime Minister of the UK?","options":["Margaret Thatcher","Theresa May","Indira Gandhi","Golda Meir"],"correctIndex":0},
{"topic":"History","questionText":"The Cold War ended in which year?","options":["1991","1989","1990","1992"],"correctIndex":0},
{"topic":"History","questionText":"Who was the leader of Nazi Germany?","options":["Adolf Hitler","Joseph Stalin","Benito Mussolini","Winston Churchill"],"correctIndex":0},
{"topic":"History","questionText":"Which civilization built Machu Picchu?","options":["Inca","Maya","Aztec","Olmec"],"correctIndex":0},
{"topic":"History","questionText":"Who invented the steam engine?","options":["James Watt","Thomas Edison","Nikola Tesla","Benjamin Franklin"],"correctIndex":0},
{"topic":"History","questionText":"The Great Depression began in which year?","options":["1929","1920","1930","1935"],"correctIndex":0},
{"topic":"History","questionText":"Who was the leader of India’s independence movement?","options":["Mahatma Gandhi","Jawaharlal Nehru","Subhash Chandra Bose","Bhagat Singh"],"correctIndex":0},
{"topic":"History","questionText":"Who was the first female ruler of England?","options":["Elizabeth I","Mary I","Victoria","Anne"],"correctIndex":0},
{"topic":"History","questionText":"Which empire built the Colosseum?","options":["Roman Empire","Greek Empire","Ottoman Empire","Persian Empire"],"correctIndex":0},
{"topic":"History","questionText":"Who was the first man on the moon?","options":["Neil Armstrong","Buzz Aldrin","Yuri Gagarin","Michael Collins"],"correctIndex":0},
{"topic":"History","questionText":"The Industrial Revolution began in which country?","options":["England","France","Germany","USA"],"correctIndex":0},
{"topic":"History","questionText":"Who led the Reign of Terror in France?","options":["Robespierre","Napoleon","Louis XVI","Danton"],"correctIndex":0},
{"topic":"History","questionText":"The Magna Carta limited the power of which ruler?","options":["King John","King Henry","Queen Elizabeth","King Richard"],"correctIndex":0},
{"topic":"History","questionText":"Who was the founder of the Ottoman Empire?","options":["Osman I","Suleiman","Mehmed II","Ataturk"],"correctIndex":0},
{"topic":"History","questionText":"The Berlin Wall was built in which year?","options":["1961","1959","1963","1965"],"correctIndex":0},
{"topic":"History","questionText":"Who was the first emperor of Rome?","options":["Augustus","Julius Caesar","Nero","Caligula"],"correctIndex":0},
{"topic":"History","questionText":"Which war ended with the Treaty of Versailles?","options":["World War I","World War II","Napoleonic Wars","Seven Years War"],"correctIndex":0},
{"topic":"History","questionText":"Who was the first ruler of the Maurya Empire?","options":["Chandragupta Maurya","Ashoka","Bindusara","Harsha"],"correctIndex":0},
{"topic":"Sports","questionText":"Which country won the FIFA World Cup in 2018?","options":["France","Croatia","Brazil","Germany"],"correctIndex":0},
{"topic":"Sports","questionText":"How many players are there in a cricket team on the field?","options":["11","10","12","9"],"correctIndex":0},
{"topic":"Sports","questionText":"In which sport is the term 'love' used?","options":["Tennis","Football","Basketball","Cricket"],"correctIndex":0},
{"topic":"Sports","questionText":"Who holds the record for most Olympic gold medals?","options":["Michael Phelps","Usain Bolt","Carl Lewis","Mark Spitz"],"correctIndex":0},
{"topic":"Sports","questionText":"Which country hosts the Wimbledon Championship?","options":["UK","USA","France","Australia"],"correctIndex":0},
{"topic":"Sports","questionText":"How long is a standard marathon?","options":["42.195 km","40 km","45 km","50 km"],"correctIndex":0},
{"topic":"Sports","questionText":"Which sport uses a shuttlecock?","options":["Badminton","Tennis","Squash","Table Tennis"],"correctIndex":0},
{"topic":"Sports","questionText":"Which country won the first FIFA World Cup?","options":["Uruguay","Brazil","Italy","Germany"],"correctIndex":0},
{"topic":"Sports","questionText":"Which player is known as 'The King of Football'?","options":["Pelé","Maradona","Messi","Ronaldo"],"correctIndex":0},
{"topic":"Sports","questionText":"How many minutes are there in a standard soccer match?","options":["90","80","100","70"],"correctIndex":0},
{"topic":"Sports","questionText":"In which sport is the term 'strike' commonly used?","options":["Bowling","Baseball","Cricket","Hockey"],"correctIndex":0},
{"topic":"Sports","questionText":"Which country won the ICC Cricket World Cup in 2019?","options":["England","New Zealand","Australia","India"],"correctIndex":0},
{"topic":"Sports","questionText":"What is the maximum score in a single frame of bowling?","options":["30","50","20","25"],"correctIndex":0},
{"topic":"Sports","questionText":"Which athlete is known as the fastest man alive?","options":["Usain Bolt","Carl Lewis","Michael Johnson","Asafa Powell"],"correctIndex":0},
{"topic":"Sports","questionText":"Which country won the Rugby World Cup in 2019?","options":["South Africa","New Zealand","England","Australia"],"correctIndex":0},
{"topic":"Sports","questionText":"Which sport is played at Lord’s Cricket Ground?","options":["Cricket","Football","Tennis","Hockey"],"correctIndex":0},
{"topic":"Sports","questionText":"In tennis, how many points are needed to win a game (without deuce)?","options":["4","3","5","6"],"correctIndex":0},
{"topic":"Sports","questionText":"Which country has won the most Olympic medals overall?","options":["USA","Russia","China","Germany"],"correctIndex":0},
{"topic":"Sports","questionText":"What is the term for a score of zero in tennis?","options":["Love","Nil","Zero","Duck"],"correctIndex":0},
{"topic":"Sports","questionText":"Which sport uses the terms 'birdie' and 'smash'?","options":["Badminton","Tennis","Squash","Volleyball"],"correctIndex":0},
{"topic":"Sports","questionText":"Which country has won the most FIFA World Cups?","options":["Brazil","Germany","Italy","Argentina"],"correctIndex":0},
{"topic":"Sports","questionText":"Which Grand Slam is played on clay courts?","options":["French Open","Wimbledon","US Open","Australian Open"],"correctIndex":0},
{"topic":"Sports","questionText":"Who is known as the 'GOAT' in basketball?","options":["Michael Jordan","LeBron James","Kobe Bryant","Magic Johnson"],"correctIndex":0},
{"topic":"Sports","questionText":"Which sport is associated with the Stanley Cup?","options":["Ice Hockey","Basketball","Baseball","Football"],"correctIndex":0},
{"topic":"Sports","questionText":"How many players are on a standard volleyball team on the court?","options":["6","5","7","8"],"correctIndex":0},
{"topic":"Sports","questionText":"Which country hosted the 2016 Summer Olympics?","options":["Brazil","China","UK","Russia"],"correctIndex":0},
{"topic":"Sports","questionText":"In golf, what is a score of one under par called?","options":["Birdie","Eagle","Bogey","Albatross"],"correctIndex":0},
{"topic":"Sports","questionText":"Which country won the first Cricket World Cup in 1975?","options":["West Indies","Australia","England","India"],"correctIndex":0},
{"topic":"Sports","questionText":"In which sport do teams compete for the Ashes?","options":["Cricket","Rugby","Football","Hockey"],"correctIndex":0},
{"topic":"Sports","questionText":"Which country is known as the origin of judo?","options":["Japan","China","Korea","Thailand"],"correctIndex":0},
{"topic":"Sports","questionText":"How long is an Olympic swimming pool?","options":["50 meters","25 meters","100 meters","75 meters"],"correctIndex":0},
{"topic":"Sports","questionText":"Which sport uses the term 'home run'?","options":["Baseball","Cricket","Tennis","Football"],"correctIndex":0},
{"topic":"Sports","questionText":"Which country has won the most Rugby World Cups?","options":["New Zealand","Australia","South Africa","England"],"correctIndex":0},
{"topic":"Sports","questionText":"In basketball, how many points is a free throw worth?","options":["1","2","3","0"],"correctIndex":0},
{"topic":"Sports","questionText":"Which country won the 2022 FIFA World Cup?","options":["Argentina","France","Brazil","Germany"],"correctIndex":0},
{"topic":"Sports","questionText":"What is the term for a perfect score in ten-pin bowling?","options":["300","250","200","275"],"correctIndex":0},
{"topic":"Sports","questionText":"Which country has won the most Olympic gold medals in gymnastics?","options":["USA","Russia","China","Japan"],"correctIndex":0},
{"topic":"Sports","questionText":"Which tennis player has the most Grand Slam titles (male)?","options":["Rafael Nadal","Roger Federer","Novak Djokovic","Pete Sampras"],"correctIndex":2},
{"topic":"Sports","questionText":"Which country hosted the first modern Olympics in 1896?","options":["Greece","France","USA","UK"],"correctIndex":0},
{"topic":"Sports","questionText":"Which sport is known as the 'king of sports'?","options":["Football","Cricket","Basketball","Tennis"],"correctIndex":0},
{"topic":"Sports","questionText":"Which player is famous for the 'Hand of God' goal?","options":["Diego Maradona","Lionel Messi","Cristiano Ronaldo","Pele"],"correctIndex":0},
{"topic":"Sports","questionText":"Which country won the 2015 Cricket World Cup?","options":["Australia","India","New Zealand","South Africa"],"correctIndex":0},
{"topic":"Sports","questionText":"In which sport is the Davis Cup awarded?","options":["Tennis","Football","Cricket","Badminton"],"correctIndex":0},
{"topic":"Sports","questionText":"Which country has won the most F1 Constructors' Championships?","options":["Ferrari","Mercedes","McLaren","Red Bull"],"correctIndex":0},
{"topic":"Sports","questionText":"How many periods are there in a standard ice hockey match?","options":["3","4","2","5"],"correctIndex":0},
{"topic":"Sports","questionText":"Which player has scored the most goals in World Cup history?","options":["Miroslav Klose","Ronaldo","Pelé","Gerd Müller"],"correctIndex":0}

];

mongoose.connect(process.env.MONGO_URI)
  .then(() => console.log("✅ MongoDB Connected"))
  .catch(err => console.error("❌ Connection Error:", err));

const seedDB = async () => {
  try {
    await Question.deleteMany({}); // Optional: clear existing questions
    await Question.insertMany(questions);
    console.log(`🎯 ${questions.length} Questions Inserted Successfully!`);
  } catch (err) {
    console.error("❌ Error inserting questions:", err);
  } finally {
    mongoose.connection.close();
  }
};

seedDB();
